[project]
name = "k40gen"
version = "0.0.1"
authors = [
  { name="Roel Aaij", email="roel.aaij@nikhef.nl" },
]
description = "KM3NeT background generator"
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel", "numpy", "cmake"]
build-backend = "setuptools.build_meta"